from __future__ import print_function
import keras
from keras.datasets import cifar10
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization
import os
from keras import regularizers
from keras.callbacks import LearningRateScheduler
import numpy as np
import os
import tensorflow as tf
from models import *


# os.environ["CUDA_VISIBLE_DEVICES"]="1"

def lr_schedule(epoch):
    lrate = 0.001
    if epoch > 75:
        lrate = 0.0005
    if epoch > 100:
        lrate = 0.0003
    return lrate

folds = 5
batch_size = 256
num_classes = 10
epochs = 25
data_augmentation = True
save_dir = os.path.join(os.getcwd(), 'saved_models1')
model_name = 'keras_cifar10_trained_model'
weight_decay = 1e-4

# The data, split between train and test sets:
(datax, datay), (x_test, y_test) = cifar10.load_data()
y_test = keras.utils.to_categorical(y_test, num_classes)
x_test = x_test.astype('float32')
x_test /=255

model = final_model()



fold_size = int(datax.shape[0] / folds)
start = 0
end = fold_size
results = np.zeros((fold_size, 6))

for i in range(folds):
    print('----------------')
    x_val = datax[start:end]
    y_val = datay[start:end]

    x_train = np.concatenate((datax[:start] , datax[end:]), axis = 0)
    y_train = np.concatenate((datay[:start] , datay[end:]), axis = 0)

    print('Model ' + str(i) + ' running ...')
    print(x_train.shape)
    print(y_train.shape)
    print(x_val.shape)
    print(y_val.shape)


    # Convert class vectors to binary class matrices.
    y_train = keras.utils.to_categorical(y_train, num_classes)
    y_val = keras.utils.to_categorical(y_val, num_classes)


    x_train = x_train.astype('float32')
    x_val = x_val.astype('float32')

    x_train /= 255
    x_val /= 255


    if not data_augmentation:
        print('Not using data augmentation.')
        model.fit(x_train, y_train,
                  batch_size=batch_size,
                  epochs=epochs,
                  validation_data=(x_val, y_val),
                  shuffle=True)
        print('Training loss: '+str(loss.history['loss'][-1]) + ',   Training Acc: '+str(loss.history['acc'][-1]))
        print('Val loss: '+str(loss.history['val_loss'][-1]) + ',   Val Acc: '+str(loss.history['val_acc'][-1]))
        scores = model.evaluate(x_test, y_test, verbose=1)
        print('Test loss:', scores[0])
        print('Test accuracy:', scores[1])
    else:
        print('Using real-time data augmentation.')
        # This will do preprocessing and realtime data augmentation:
        datagen = ImageDataGenerator(
            featurewise_center=False,  # set input mean to 0 over the dataset
            samplewise_center=False,  # set each sample mean to 0
            featurewise_std_normalization=False,  # divide inputs by std of the dataset
            samplewise_std_normalization=False,  # divide each input by its std
            zca_whitening=False,  # apply ZCA whitening
            zca_epsilon=1e-06,  # epsilon for ZCA whitening
            rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
            # randomly shift images horizontally (fraction of total width)
            width_shift_range=0.1,
            # randomly shift images vertically (fraction of total height)
            height_shift_range=0.1,
            shear_range=0.,  # set range for random shear
            zoom_range=0.,  # set range for random zoom
            channel_shift_range=0.,  # set range for random channel shifts
            # set mode for filling points outside the input boundaries
            fill_mode='nearest',
            cval=0.,  # value used for fill_mode = "constant"
            horizontal_flip=True,  # randomly flip images
            vertical_flip=False,  # randomly flip images
            # set rescaling factor (applied before any other transformation)
            rescale=None,
            # set function that will be applied on each input
            preprocessing_function=None,
            # image data format, either "channels_first" or "channels_last"
            data_format=None,
            # fraction of images reserved for validation (strictly between 0 and 1)
            validation_split=0.0)

        # Compute quantities required for feature-wise normalization
        # (std, mean, and principal components if ZCA whitening is applied).
        datagen.fit(x_train)
        train_steps_per_epoch = x_train.shape[0]/batch_size

        # Fit the model on the batches generated by datagen.flow().
        loss = model.fit_generator(datagen.flow(x_train, y_train,
                                         batch_size=batch_size),
                            epochs=epochs,
                            steps_per_epoch=train_steps_per_epoch,
                            validation_data=(x_val, y_val),
                            workers=4,
                            callbacks=[LearningRateScheduler(lr_schedule)])
        # print(loss.history.keys())
        print('Training loss: '+str(loss.history['loss'][-1]) + ',   Training Acc: '+str(loss.history['acc'][-1]))
        print('Val loss: '+str(loss.history['val_loss'][-1]) + ',   Val Acc: '+str(loss.history['val_acc'][-1]))
        scores = model.evaluate(x_test, y_test, verbose=1)
        print('Test loss:', scores[0])
        print('Test accuracy:', scores[1])
        results[i,0] = loss.history['loss'][-1]
        results[i,1] = loss.history['acc'][-1]
        results[i,2] = loss.history['val_loss'][-1]
        results[i,3] = loss.history['val_acc'][-1]
        results[i,4] = scores[0]
        results[i,5] = scores[1]


    # Save model and weights
    if not os.path.isdir(save_dir):
        os.makedirs(save_dir)
    model_path = os.path.join(save_dir, model_name+str(i)+'.h5')
    # model.save(model_path)
    # print('Saved trained model at %s ' % model_path)

print('**********************K-FOLD RESULTS************************')
results = np.sum(results, axis = 0)/folds
print('Training loss: '+ str(results [0]) + ',   Training Acc: '+ str(results [1]))
print('Val loss: '+ str(results [2]) + ',   Val Acc: '+ str(results [3]))
print('Test loss: '+ str(results [4]) + ',   Test Acc: '+ str(results [5]))
